import { ArrowLeft, ArrowRight, DownloadSimple, ShareNetwork } from '@phosphor-icons/react'

export function IdentityResult({ result, faceImage, onBack, onApply }) {
  const shareCard=async()=>{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const c=canvas.getContext('2d');c.fillStyle='#f5f0e7';c.fillRect(0,0,1080,1350);c.fillStyle='#1b1714';c.font='30px Georgia';c.fillText('MY VISUAL IDENTITY',70,90);c.fillStyle='#7b0b0e';c.font='74px Georgia';c.fillText(result.primaryEn,70,235);c.fillStyle='#1b1714';c.font='28px sans-serif';c.fillText(`People see you as: ${result.traits.join(' · ')}`,72,310);c.strokeStyle='#9c9184';c.strokeRect(70,390,940,400);c.font='24px sans-serif';c.fillText('BEST GLASSES STYLE',100,455);c.font='56px Georgia';c.fillText(result.recommendations[0].name,100,555);c.font='25px sans-serif';result.scenarioMatches.forEach(([scene,score],i)=>c.fillText(`${scene}  ${score}%`,100,650+i*55));c.font='30px Georgia';c.fillText('Which version of me do you prefer?',70,1190);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const file=new File([blob],'my-visual-identity.png',{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:'My Visual Identity',files:[file]});else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click()}}
  return <main className="identity-result-page editorial-page">
    <button className="detail-back" onClick={onBack}><ArrowLeft/> BACK TO TEST</button>
    <section className="identity-cover"><img src={faceImage} alt="视觉身份肖像"/><div><span>MY VISUAL IDENTITY · ISSUE 03</span><h1>{result.primaryEn}</h1><blockquote>{result.aura}</blockquote><div>{result.traits.map(t=><i key={t}>{t}</i>)}</div></div></section>
    <section className="identity-editorial"><div className="identity-drivers"><span>YOUR INNER DRIVERS</span><h2>你的心理驱动</h2>{result.drivers.map((item,index)=><p key={item}><b>0{index+1}</b>{item}</p>)}</div><div className="identity-enhance"><span>VISUAL DIRECTION</span><strong>{result.strategy}</strong><h2>放大你的稳定感</h2><p>通过比例、材质和线条，让镜框成为你原有气质的清晰延伸，而不是遮挡。</p></div></section>
    <section className="identity-frame-list"><header><span>CURATED FOR YOU</span><h2>Three frames, three expressions.</h2></header><div>{result.recommendations.map((frame,index)=><article key={frame.name}><span>0{index+1}</span><img src={`${import.meta.env.BASE_URL}glasses-${frame.styleIndex+1}.png`} alt={frame.name}/><div><h3>{frame.name}</h3><p>{frame.reason}</p><div>{frame.tags.map(t=><i key={t}>{t}</i>)}</div></div><b>{frame.identityScore}%</b><button onClick={()=>onApply(result,frame)}>Try This Style <ArrowRight/></button></article>)}</div></section>
    <section className="share-identity"><div><span>SHAREABLE EDITION</span><h2>Which version of me<br/>do you prefer?</h2></div><div className="share-card"><small>MY VISUAL IDENTITY</small><strong>{result.primaryEn}</strong><p>People see you as<br/>{result.traits.join(' · ')}</p><hr/><small>BEST GLASSES STYLE</small><b>{result.recommendations[0].name}</b>{result.scenarioMatches.map(([s,n])=><i key={s}>{s}<em>{n}%</em></i>)}</div><button onClick={shareCard}><ShareNetwork/> Share My Identity <DownloadSimple/></button></section>
  </main>
}
